# Generated by Django 2.1 on 2018-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_qouta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qouta',
            field=models.PositiveIntegerField(),
        ),
    ]
